### ISSUE TITLE
Library looses key bindings after Windows lock screen

### ISSUE THREAD

**Issue by BakuDev** [kfirprods/NonInvasiveKeyboardHook#1]
Hi there!
First of all - big thanks for this great library!
I noticed a bug: once windows is locked (Win+L) and unlocked, a hot key binding is lost then.
I'm using this lib in screenshot app which is being used in domain, so I'm not sure if this is repeatable in ordinary non-domain environment. 
Please add auto rebind feature or a method to check if a key binding is still alive.
Regards!

**Comment by kfirprods** [comment]
Thanks for the input. I will try to look into it, but cannot promise to be available to do that soon. You are welcome to do this change in a pull request :)

**Comment by BakuDev** [comment]
As a workaround you may use the following code:

// LISTEN TO SESSION SWITCH EVENTS
SystemEvents.SessionSwitch += SystemEvents_SessionSwitch;

// REINIT INSTANCE AND REBIND KEYS
public void SystemEvents_SessionSwitch(object sender, SessionSwitchEventArgs e)
        {
            if (e.Reason == SessionSwitchReason.SessionUnlock)
            {
                SetupKeyboardKeysOnceAgain(); // PSEUDO CODE
            }
        }

**Comment by kfirprods** [comment]
Thank you for suggesting a solution to your problem (and sorry for the one-year delay)!
I'll look into the possibility of handling this event in the library
