### ISSUE TITLE
ALT+F4 like combination

### ISSUE THREAD

**Issue by mhnowak** [kfirprods/NonInvasiveKeyboardHook#2]
Hey, so I'm trying to implement ALT+F4 like global hotkey . And I've got this so far: 
```c#
                    var keyboardHookManager = new KeyboardHookManager();
                    keyboardHookManager.Start();

                    keyboardHookManager.RegisterHotkey(ModifierKeys.Alt, 115, () =>
                    {
                        // do smth
                    });
```
The problem with that `do smth` is not called everytime and you there's a way to call ALT+F4 hotkey (regular one) without executing the code inside. So far I've noticed that the issue occurs when you press ALT + F4 very fast and u start releasing ALT (button) while pressing F4 (I'm not sure if that makes sense). I'm using mechanical keyboard, but I assume it shouldn't be making whole lots of a difference (but maybe it helps with reproducing). 

Anyway can you maybe point me in the right direction why it happens? I'm willing to make changes leaving a PR if needed or forking the library to make necessary changes for my own use, even tho I'm not really keen in C#.

**Comment by kfirprods** [comment]
I'll give it a try myself. If I manage to replicate this, I'll look into what we can do here.

A question about the part where you said "there's a way to call ALT+F4 without executing the code inside": is it specifically ALT+F4 on your own app's window, or did this happen no matter where ALT+F4 was being called?

In addition, if you're trying to **prevent** the regular ALT+F4 from happening, then this library is not the way to get there.

**Comment by mhnowak** [comment]
To clarify:
1. It's not Alt+f4 on my app window (I'm not interested in this case as my app doesn't have window, it runs in the background - which I assume could be the reason).
2. I'm not trying to prevent that, just doing one thing on top of that.
3. I'm running a shell command that could potentially slow that, but this shouldn't prevent the app function to execute. 

I wanted to do more testing with the library later this weekend as I didn't really have time this week. 

However if you'd like to investigate more on yourself there's a public repository on my GitHub called LoLkiller - I appreciate any code reviews etc. You could get the base of what I'm talking about from there or just wait for me to add some simpler version to reproduce that.

**Comment by kfirprods** [comment]
Thank you for the clarification, and for pointing out the project that you're using this library for. P.S. - my original use case was a background app for a game too 😄 

I'd like to point out this example WPF app that uses the library: https://github.com/kfirprods/ShortcutHotkeysExample
I managed to replicate what you described here very easily on that app. If "ALT" key is held for too short a time, the keybind doesn't get triggered.

The same goes for other modifiers (Ctrl, Shift and WinKey), so then I know that the problem has to do with the way that I detect modifiers. I'll look into it and let you know if I find anything :)

**Comment by kfirprods** [comment]
I think I found the root cause for which issue just by looking at the code. I'll test it tomorrow, but anyway the place to look is the private `HandleSingleKeyboardInput` function of the 
 `KeyboardHookManager` class, where modifier keys are handled.

The problem probably stems from the fact that I only trigger key events when on **KeyUp** events. So in the case of Alt+F4, you release Alt before you release F4 (i.e. KeyUp runs for Alt before it runs for F4)

The solution is to trigger key events on **KeyDown** events. However, the system will report `KeyDown` repeatedly as long as a key is being held down, so it's important to trigger the key event only once per keypress.

**Comment by kfirprods** [comment]
@mhnowak  I had just released v2.0.0
Update the nuget package in your project and let me know if it works :)

**Comment by mhnowak** [comment]
Thanks I tried that and it seems to work better now. At least I didn't manage to break it this time 😅

**Comment by kfirprods** [comment]
> Thanks I tried that and it seems to work better now. At least I didn't manage to break it this time 😅

I'm glad to hear that :)
