### ISSUE TITLE
RegisterHotKey doesn't work properly with modifier keys

### ISSUE THREAD

**Issue by JoshuaNS** [kfirprods/NonInvasiveKeyboardHook#3]
Tried a test application with this library,
Registered Control+b, Alt+b, Shift+b as with separate actions

Noticed They became 
Alt+Control
Alt
Alt+Shift

This is because of your use of them as flags when the ModiferKeys overlap on a bitwise level.
`              var selectedModifiers = allModifiers.Where(modifier => modifiers.HasFlag(modifier)).ToArray();`
Alt will always be a selected modifier because HasFlag(0) is always true.

I would recommend changing the values of ModifierKey enum to the following, unless it has some other impact on your code.
Alt=1
Control=2
Shift=4
WindowsKey=8

**Comment by kfirprods** [comment]
Wow, what a rookie mistake on my behalf 😅  
thank you for pointing this issue out and providing the solution alongside it.
I'll release v2.1 shortly

**Comment by kfirprods** [comment]
Fixed in v2.1
