### ISSUE TITLE
2.1.1, cooperation with X-Mouse Button Control

### ISSUE THREAD

**Issue by 0xotHik** [kfirprods/NonInvasiveKeyboardHook#8]
Hello,

It's not the "issue" issue, I guess, just wanted you to know, maybe you've encountered that.
I use X-Mouse Button Control to emulate pressing the keyboard key, registred as Hotkey in NIKH, and that worked fine in previous version of NIKH (that was the time, when NIKH reacted when I release the key, not like now, when the key down is enough), but now pressing the key on the keyboard is working fine, but X-Mouse Button Control somewhy is not, as normal simulation. If I click twice, or emulating pressing the keyboard key twice, or emulating pressing, holding for 50ms, and then releasing — it's working.

**Comment by kfirprods** [comment]
Hey man. Tell me if I understood correctly: you had to use the described workaround to get X-Mouse Button Control to trigger a callback that you set up with `NIKH` (P.S. kudos on the abbreviation), and that only began when you started using NIKH v2 (where I introduced a compatibility breaking change), is that correct?

First, I should admit it is my fault that I did not at least keep some optional boolean parameter to allow explicitly choosing the old "on-key-up" behavior. If you want, you can create a pull request that implements that change and we'll release a new minor version with it.

Secondly, you can try to debug NIKH (TIP: you can use an existing project that has a UI like this sample https://github.com/kfirprods/ShortcutHotkeysExample). I would set breakpoints in the handlers of the main events (key down, key up) too find out what's what. The code is short and straightforward :)

**Comment by 0xotHik** [comment]
Yeah, if I set in X-Mouse Button Control not to just emulate the pressing of the key, I register as hotkey in NIKH, but to emulate it pressing twice, or pressing and holding for 50ms — it's working with the new version. If I set to just simulate the pressing once — not working. I have to press the mouse button one more time.
(If I emulate to press and hold for 1ms — not working either)

I don't think it is a problem, cause I just emulate pressing the key twice, but I was just wondering, maybe you know, why it working this way :)

**Comment by kfirprods** [comment]
I am curious to find that out, but unfortunately don't have the extra time to debug this. This has to be somewhat related to the way that X-Mouse Button Control triggers events - they're either sending an unexpected sequence of Up/Down events, or perhaps sending the events instantly one right after the other
